<?php
/**
 * Giftia Admin Settings Panel v6.0
 * 
 * Gestiona todas las variables de entorno (.env) desde el panel de WordPress.
 * Lee/escribe del archivo .env, fallback a wp_options si .env no existe.
 * 
 * Variables soportadas:
 * - WP_API_TOKEN: Token de autenticación para la API de ingesta
 * - GEMINI_API_KEY: Clave API de Google Gemini
 * - AMAZON_TAG: ID de afiliado de Amazon
 * - ALLOWED_ORIGINS: CORS whitelist (JSON array)
 * - DEBUG: Modo debug (0|1)
 */

if ( ! defined( 'ABSPATH' ) ) exit;

// ============================================================================
// FUNCIONES DE GESTIÓN .ENV
// ============================================================================

/**
 * Obtiene la ruta del archivo .env
 */
function gf_get_env_file_path() {
    // Opciones de búsqueda en orden de preferencia
    $paths = array(
        dirname( dirname( dirname( __FILE__ ) ) ) . '/.env',  // wp-content/../.env
        dirname( dirname( __FILE__ ) ) . '/.env',            // wp-content/.env
        dirname( __FILE__ ) . '/.env',                       // plugin/.env
        $_SERVER['DOCUMENT_ROOT'] . '/.env',                 // /var/www/html/.env
        '/var/www/html/.env',                                // Default shared hosting
    );
    
    foreach ( $paths as $path ) {
        if ( file_exists( $path ) && is_writable( $path ) ) {
            return $path;
        }
    }
    
    // Si ninguno existe, crear en la raíz de WordPress
    $wp_root = dirname( dirname( dirname( __FILE__ ) ) ) . '/.env';
    return $wp_root;
}

/**
 * Lee todas las variables del archivo .env
 */
function gf_read_env_file() {
    $env_file = gf_get_env_file_path();
    $env_vars = array();
    
    if ( file_exists( $env_file ) && is_readable( $env_file ) ) {
        $lines = file( $env_file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES );
        foreach ( $lines as $line ) {
            if ( strpos( $line, '#' ) === 0 ) continue; // Skip comments
            if ( strpos( $line, '=' ) === false ) continue;
            
            list( $key, $value ) = explode( '=', $line, 2 );
            $key = trim( $key );
            $value = trim( $value );
            
            // Remove quotes if present
            if ( ( $value[0] ?? '' ) === '"' ) {
                $value = substr( $value, 1, -1 );
            }
            
            $env_vars[ $key ] = $value;
        }
    }
    
    return $env_vars;
}

/**
 * Escribe variables al archivo .env
 */
function gf_write_env_file( $variables ) {
    $env_file = gf_get_env_file_path();
    
    // Leer variables existentes
    $existing = gf_read_env_file();
    
    // Merged with new values
    $all_vars = array_merge( $existing, $variables );
    
    // Construir contenido del archivo
    $content = "# Giftia Environment Configuration\n";
    $content .= "# Auto-generated by WordPress Admin Panel\n";
    $content .= "# Generated: " . current_time( 'mysql' ) . "\n\n";
    
    foreach ( $all_vars as $key => $value ) {
        if ( empty( $value ) ) continue;
        
        // Quote values with spaces
        if ( strpos( $value, ' ' ) !== false || strpos( $value, ',' ) !== false ) {
            $value = '"' . $value . '"';
        }
        
        $content .= "{$key}={$value}\n";
    }
    
    // Ensure directory exists and is writable
    $dir = dirname( $env_file );
    if ( ! is_dir( $dir ) ) {
        mkdir( $dir, 0755, true );
    }
    
    // Write file
    $result = @file_put_contents( $env_file, $content );
    
    if ( $result === false ) {
        return new WP_Error( 'env_write_failed', 'No se pudo escribir el archivo .env. Verifica permisos.' );
    }
    
    // Ensure proper permissions
    @chmod( $env_file, 0644 );
    
    // Log action
    gf_log( "Environment variables saved to {$env_file}", 'info' );
    
    return true;
}

// ============================================================================
// HOOKS DE ADMINISTRACIÓN
// ============================================================================

add_action( 'admin_menu', 'gf_add_admin_menu' );
add_action( 'admin_init', 'gf_process_settings_form' );

function gf_add_admin_menu() {
    add_submenu_page(
        'edit.php?post_type=gf_gift',
        'Giftia Settings',
        '⚙️ Configuración',
        'manage_options',
        'gf-settings',
        'gf_render_settings_page'
    );
}

function gf_process_settings_form() {
    if ( ! isset( $_POST['gf_settings_nonce'] ) ) return;
    if ( ! wp_verify_nonce( $_POST['gf_settings_nonce'], 'gf_settings_action' ) ) return;
    if ( ! current_user_can( 'manage_options' ) ) return;
    
    // Recolectar variables
    $env_vars = array();
    
    // WP_API_TOKEN
    if ( isset( $_POST['gf_wp_api_token'] ) && ! empty( $_POST['gf_wp_api_token'] ) ) {
        $env_vars['WP_API_TOKEN'] = sanitize_text_field( $_POST['gf_wp_api_token'] );
    }
    
    // GEMINI_API_KEY
    if ( isset( $_POST['gf_gemini_api_key'] ) && ! empty( $_POST['gf_gemini_api_key'] ) ) {
        $env_vars['GEMINI_API_KEY'] = sanitize_text_field( $_POST['gf_gemini_api_key'] );
    }
    
    // AMAZON_TAG
    if ( isset( $_POST['gf_amazon_tag'] ) && ! empty( $_POST['gf_amazon_tag'] ) ) {
        $env_vars['AMAZON_TAG'] = sanitize_text_field( $_POST['gf_amazon_tag'] );
    }
    
    // ALLOWED_ORIGINS (JSON)
    if ( isset( $_POST['gf_allowed_origins'] ) && ! empty( $_POST['gf_allowed_origins'] ) ) {
        $origins = sanitize_textarea_field( $_POST['gf_allowed_origins'] );
        $origins_array = array_map( 'trim', explode( '\n', $origins ) );
        $origins_array = array_filter( $origins_array, function( $x ) { return ! empty( $x ); } );
        $env_vars['ALLOWED_ORIGINS'] = json_encode( $origins_array );
    }
    
    // DEBUG
    $env_vars['DEBUG'] = isset( $_POST['gf_debug'] ) ? '1' : '0';
    
    // Guardar al .env
    $result = gf_write_env_file( $env_vars );
    
    // TAMBIÉN guardar en wp_options como respaldo
    foreach ( $env_vars as $key => $value ) {
        $option_key = 'gf_' . strtolower( $key );
        update_option( $option_key, $value );
    }
    
    if ( is_wp_error( $result ) ) {
        add_action( 'admin_notices', function() use ( $result ) {
            echo '<div class="notice notice-error"><p><strong>Error:</strong> ' . esc_html( $result->get_error_message() ) . '</p></div>';
        });
    } else {
        add_action( 'admin_notices', function() {
            echo '<div class="notice notice-success is-dismissible"><p>✅ Variables de entorno guardadas correctamente.</p></div>';
        });
    }
}

// ============================================================================
// RENDERING DEL PANEL
// ============================================================================

function gf_render_settings_page() {
    if ( ! current_user_can( 'manage_options' ) ) {
        wp_die( 'No tienes permiso.' );
    }
    
    // Leer valores actuales
    $env_vars = gf_read_env_file();
    $env_file = gf_get_env_file_path();
    $env_exists = file_exists( $env_file );
    $env_writable = is_writable( dirname( $env_file ) );
    
    // Cargar valores con fallback a wp_options
    $wp_token = $env_vars['WP_API_TOKEN'] ?? get_option( 'gf_wp_api_token', '' );
    $gemini_key = $env_vars['GEMINI_API_KEY'] ?? get_option( 'gf_gemini_api_key', '' );
    $amazon_tag = $env_vars['AMAZON_TAG'] ?? get_option( 'gf_amazon_tag', 'GIFTIA-21' );
    $allowed_origins = $env_vars['ALLOWED_ORIGINS'] ?? '[]';
    $debug = $env_vars['DEBUG'] ?? '0';
    
    // Parse allowed origins
    $origins_array = json_decode( $allowed_origins, true ) ?? array();
    $origins_text = implode( "\n", $origins_array );
    
    ?>
    <div class="wrap gf-admin-wrap">
        <h1>⚙️ Configuración de Giftia</h1>
        
        <!-- Status Box -->
        <div style="background: #f5f5f5; border-left: 4px solid <?php echo $env_writable ? '#28a745' : '#dc3545'; ?>; padding: 15px; margin-bottom: 20px; border-radius: 4px;">
            <p><strong>📁 Archivo .env:</strong> <code><?php echo esc_html( $env_file ); ?></code></p>
            <p>
                <strong>Estado:</strong>
                <?php if ( $env_exists ): ?>
                    <span style="color: #28a745;">✅ Existe</span>
                <?php else: ?>
                    <span style="color: #ffc107;">⚠️ No existe (será creado)</span>
                <?php endif; ?>
                
                <?php if ( $env_writable ): ?>
                    <span style="color: #28a745;">✅ Escribible</span>
                <?php else: ?>
                    <span style="color: #dc3545;">❌ No escribible</span>
                <?php endif; ?>
            </p>
            <p style="font-size: 12px; margin-top: 10px;">
                <strong>💡 Tip:</strong> El archivo .env está fuera del directorio public para mayor seguridad.
                Si no existe, se creará automáticamente al guardar.
            </p>
        </div>
        
        <!-- Settings Form -->
        <form method="post" action="" style="max-width: 600px;">
            <?php wp_nonce_field( 'gf_settings_action', 'gf_settings_nonce' ); ?>
            
            <table class="form-table">
                
                <!-- WP_API_TOKEN -->
                <tr>
                    <th scope="row">
                        <label for="gf_wp_api_token">🔐 Token de API (WP_API_TOKEN)</label>
                    </th>
                    <td>
                        <input 
                            type="password" 
                            id="gf_wp_api_token" 
                            name="gf_wp_api_token" 
                            value="<?php echo esc_attr( $wp_token ); ?>" 
                            class="regular-text code"
                            placeholder="Dejar vacío para generar uno aleatorio"
                        >
                        <p class="description">Token secreto para autenticar la API de ingesta de productos (Hunter).</p>
                    </td>
                </tr>
                
                <!-- GEMINI_API_KEY -->
                <tr>
                    <th scope="row">
                        <label for="gf_gemini_api_key">🤖 Clave API Gemini (GEMINI_API_KEY)</label>
                    </th>
                    <td>
                        <input 
                            type="password" 
                            id="gf_gemini_api_key" 
                            name="gf_gemini_api_key" 
                            value="<?php echo esc_attr( $gemini_key ); ?>" 
                            class="regular-text code"
                        >
                        <p class="description">
                            Clave de Google Gemini para generar descripciones IA. 
                            <a href="https://aistudio.google.com/app/apikeys" target="_blank">Obtener clave →</a>
                        </p>
                    </td>
                </tr>
                
                <!-- AMAZON_TAG -->
                <tr>
                    <th scope="row">
                        <label for="gf_amazon_tag">🛍️ ID de Afiliado Amazon (AMAZON_TAG)</label>
                    </th>
                    <td>
                        <input 
                            type="text" 
                            id="gf_amazon_tag" 
                            name="gf_amazon_tag" 
                            value="<?php echo esc_attr( $amazon_tag ); ?>" 
                            class="regular-text code"
                            placeholder="ejemplo-21"
                        >
                        <p class="description">
                            Tu ID de afiliado de Amazon. Se añade a todos los enlaces 
                            para rastrear comisiones. Formato: <code>midominio-21</code>
                        </p>
                    </td>
                </tr>
                
                <!-- ALLOWED_ORIGINS -->
                <tr>
                    <th scope="row">
                        <label for="gf_allowed_origins">🔗 CORS - Orígenes Permitidos (ALLOWED_ORIGINS)</label>
                    </th>
                    <td>
                        <textarea 
                            id="gf_allowed_origins" 
                            name="gf_allowed_origins" 
                            class="large-text code" 
                            rows="4"
                            placeholder="https://example.com&#10;https://app.example.com"
                        ><?php echo esc_textarea( $origins_text ); ?></textarea>
                        <p class="description">
                            Un origen por línea. Estos dominios pueden acceder a la API.
                            Tu dominio WordPress se incluye automáticamente.
                        </p>
                    </td>
                </tr>
                
                <!-- DEBUG -->
                <tr>
                    <th scope="row">
                        <label for="gf_debug">🐛 Modo Debug (DEBUG)</label>
                    </th>
                    <td>
                        <input 
                            type="checkbox" 
                            id="gf_debug" 
                            name="gf_debug" 
                            value="1" 
                            <?php checked( $debug, '1' ); ?>
                        >
                        <label for="gf_debug">Habilitar modo debug (logs detallados en wp-content/giftia-debug.log)</label>
                        <p class="description">Solo usa en desarrollo. Desactiva en producción.</p>
                    </td>
                </tr>
                
            </table>
            
            <?php submit_button( '💾 Guardar Configuración', 'primary', 'submit', true ); ?>
        </form>
        
        <!-- Info Box -->
        <div style="background: #e7f3ff; border: 1px solid #b3d9ff; border-radius: 4px; padding: 15px; margin-top: 30px;">
            <h3>ℹ️ Información de Configuración</h3>
            <ul style="list-style-position: inside;">
                <li><strong>Ubicación .env:</strong> Las variables se guardan en <code><?php echo basename( $env_file ); ?></code></li>
                <li><strong>Fallback:</strong> Si el archivo no existe, usa la base de datos de WordPress</li>
                <li><strong>Seguridad:</strong> El archivo .env NO debe estar en wp-content (está fuera del alcance público)</li>
                <li><strong>Hunter.py:</strong> Lee WP_API_TOKEN y AMAZON_TAG de las variables de entorno</li>
                <li><strong>API Ingest:</strong> Valida el token contra X-GIFTIA-TOKEN header</li>
            </ul>
        </div>
        
        <!-- Debug Info -->
        <?php if ( $debug == '1' ): ?>
            <div style="background: #fff3cd; border: 1px solid #ffc107; border-radius: 4px; padding: 15px; margin-top: 20px;">
                <h3>🐛 Variables Cargadas (Debug)</h3>
                <pre style="background: #f5f5f5; padding: 10px; border-radius: 3px; overflow-x: auto; max-height: 300px;">
<?php 
$safe_vars = array_map( function( $k, $v ) {
    if ( strpos( $k, 'KEY' ) !== false || strpos( $k, 'TOKEN' ) !== false ) {
        return $k . '=***' . substr( $v, -4 );
    }
    return $k . '=' . $v;
}, array_keys( $env_vars ), array_values( $env_vars ) );

echo esc_html( implode( "\n", $safe_vars ) );
?>
                </pre>
            </div>
        <?php endif; ?>
        
    </div>
    
    <style>
        .gf-admin-wrap {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
        }
        .form-table th {
            width: 250px;
        }
        code {
            background: #f5f5f5;
            padding: 2px 5px;
            border-radius: 3px;
            font-size: 13px;
        }
    </style>
    <?php
}

// Auto-generate token if missing
function gf_ensure_token_exists() {
    $env_vars = gf_read_env_file();
    if ( empty( $env_vars['WP_API_TOKEN'] ) && ! get_option( 'gf_wp_api_token' ) ) {
        $token = bin2hex( random_bytes( 16 ) );
        gf_write_env_file( array( 'WP_API_TOKEN' => $token ) );
        update_option( 'gf_wp_api_token', $token );
    }
}
add_action( 'admin_init', 'gf_ensure_token_exists' );

?>